apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-manager-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: claudie-sveltos-integration
    app.kubernetes.io/part-of: claudie-sveltos-integration
    app.kubernetes.io/managed-by: kustomize
  name: controller
  namespace: projectsveltos
