name: main
on:
  workflow_dispatch:
  push:
    branches:
    - 'main'
    - 'dev'
  pull_request:
    types: [opened, edited, synchronize, reopened]


jobs:
  build-static-test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Set up Go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # tag=v5.0.0
      with:
        go-version: 1.21.5
    - name: Build
      run: make build
    - name: FMT
      run: make fmt
    - name: VET
      run: make vet
    - name: LINT
      run: make lint
      env:
        LINT: true
  build-ut:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Set up Go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # tag=v5.0.0
      with:
        go-version: 1.21.5
    - name: ut
      run: make test
      env:
        UT: true
  FV:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Set up Go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # tag=v5.0.0
      with:
        go-version: 1.21.5
    - name: fv
      run: make create-cluster fv
      env:
        FV: true